cg_model: CalphaBasedModel
embedding_module:
  embedding_dim: 40
  num_embeddings: 22
globals:
  loss_weight:
    FAPE_CA: 5.0
    FAPE_all: 5.0
    atomic_clash: 5.0
    bonded_energy: 1.0
    distance_matrix: 0.0
    mse_R: 0.0
    rigid_body: 1.0
    rotation_matrix: 1.0
    torsion_angle: 2.0
    torsion_energy: 0.05
    v_cntr: 1.0
  num_recycle: 1
  radius: 1.0
structure_module:
  channels_div: 2
  fiber_edge:
  - !!python/tuple
    - 0
    - 3
  fiber_hidden:
  - !!python/tuple
    - 0
    - 32
  - !!python/tuple
    - 1
    - 32
  - !!python/tuple
    - 2
    - 32
  fiber_in:
  - !!python/tuple
    - 0
    - 56
  - !!python/tuple
    - 1
    - 4
  fiber_out:
  - !!python/tuple
    - 0
    - 16
  - !!python/tuple
    - 1
    - 3
  fiber_pass:
  - - 0
    - 64
  - - 1
    - 32
  loss_weight:
    FAPE_CA: 5.0
    FAPE_all: 0.0
    atomic_clash: 0.0
    bonded_energy: 1.0
    distance_matrix: 0.0
    mse_R: 0.0
    rigid_body: 1.0
    rotation_matrix: 1.0
    torsion_angle: 2.0
    v_cntr: 1.0
  low_memory: true
  nonlinearity: relu
  norm:
  - true
  - true
  num_channels: 32
  num_degrees: 3
  num_graph_layers: 4
  num_heads: 8
  num_linear_layers: 4
train:
  batch_size: 4
  crop_size: 512
  dataset: pdb.top8000
  lr: 0.001
