name: ml
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - cudatoolkit=11.3
  - python
  - biopython 
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - pytorch=1.11
  - pytorch-lightning
  - mdtraj
  - openmm
  - tqdm
  - pip
  - pip:
    - e3nn
    - ml_collections
    - torch-cluster==1.6.0
    - torch-geometric==2.0.4
    - torch-scatter==2.0.9
    - torch-sparse==0.6.13
    - torch-spline-conv==1.2.1
