name: dgl
channels:
  - conda-forge
  - defaults
  - pytorch
  - dglteam
dependencies:
  - cudatoolkit=11.3
  - python
  - biopython 
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - pytorch=1.11.0
  - pytorch-lightning
  - mdtraj
  - openmm
  - tqdm
  - pip
  - psutil
  - dgl-cuda11.3
  - pip:
    - e3nn
    - ml_collections
